### ISSUE TITLE
fatal error: ns3/krop-module.h: No such file or directory

### ISSUE THREAD

**Issue by 2280778712** [ramisa2108/NS3-AODV-Optimized-Route-Discovery-Using-K-Means-Clustering#1]
```
[2067/2125] Compiling scratch/aodvKmeansExample.cc
../scratch/aodvKmeansExample.cc:37:10: fatal error: ns3/krop-module.h: No such file or directory
 #include "ns3/krop-module.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This problem occurred when I was running your project. Can you solve it? I can't find this file anywhere.

**Comment by ramisa2108** [comment]
It was an old version of the file. I have updated it. You should be able to run it now after adding "aodvKmeans" as a module in your ns3.

**Comment by 7keqi** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/112915732/221562873-638d916c-5b06-477e-b230-6dbb35560dcf.png">
