### ISSUE TITLE
Question for AODV

### ISSUE THREAD

**Issue by Carla-33** [ramisa2108/NS3-AODV-Optimized-Route-Discovery-Using-K-Means-Clustering#2]
Hi,
Sorry I need your help if you can:
 I have some questions for that:
1- Can I integrate the Cooja with ns3?
2- Could you please lead me on how to build a Malicious Nodes in a given route (AODV)?
3-Could you tell me how to use a specific algorithm such as Naive Bayes classifier in AODV rather than K-mean?

Thank you

**Comment by ramisa2108** [comment]
1. I haven't worked with Cooja before. Can't help you, sorry.
2. You can define the behavior of a malicious node in the routing protocol class and mark some nodes randomly as malicious. There are many implementations available on Github if you are looking for something like a blackhole attack.
3. I added the K-means classifier ![here](https://github.com/ramisa2108/NS3-AODV-Optimized-Route-Discovery-Using-K-Means-Clustering/blob/e9db50adcec69b9fbfc70ba0b6a1de639fa0a929/aodvKmeans/model/aodvKmeans-rtable.cc#L391) in my code for selective forwarding of RREQ message. If you intend to do something similar, you can just replace the K-means code with your implementation of Naive Bayes.

**Comment by Carla-33** [comment]
Thank you for response.

when I have been run your own code, I got this error.
wscript:48: Warning: (in aodvKmeans) Requested to build modular python bindings, but apidefs dir not found => skipped the bindings.
  config_file_exists = False
[ 968/2726] Compiling scratch/aodvKmeans.cc
../scratch/aodvKmeans.cc:25:35: fatal error: ns3/aodvKmeans-module.h: No such file or directory
compilation terminated.

**Comment by ramisa2108** [comment]
You probably haven't built the new module correctly.
Add the aodvKmeans folder to ns3/contrib and run `make configure` followed by `make`.

**Comment by Carla-33** [comment]
Could you please tell me what Ubuntu system version you are using? I think my system is older than yours.
Could you explain more the difference between wifi-high-rate-aodv-example and wifi-low-rate-aodv-example?

Thank a lot....

**Comment by ramisa2108** [comment]
I'm using Ubuntu 20.04.
wifi-high-rate and low-rate examples are demonstrations of low-rate personal area networks and high-rate LANs in ns3. They are not exactly related to using Kmeans in AODV.
