### ISSUE TITLE
Question about Gnuplot

### ISSUE THREAD

**Issue by Carla-33** [ramisa2108/NS3-AODV-Optimized-Route-Discovery-Using-K-Means-Clustering#4]
Hi dear Ramisa:

Could you please tell me how you did you doing plotting graphs?
Could you please explain a little bit?

Thanks a lot for help me.

**Comment by ramisa2108** [comment]
I actually didn't use Gnuplot. I used flow-monitor to generate the ouput metrics (throughput, delay etc.) and then plotted the graphs using a python script that calls the plotting functions from the matplotlib library.

**Comment by Carla-33** [comment]
Hi, ramisa <https://github.com/ramisa2108>

Could you please explain the performance measurements in detail as it
shows in the code program? I want to understand what each sentence means.





·      for (auto iter = stats.begin (); iter != stats.end (); ++iter)

In here what do you mean of iter in this sentence?



·      AvgThroughput = AvgThroughput * 8.0 / ((m_totalTime-1.0) * 1024.0);

AvgThroughput = AvgThroughput + iter->second.rxBytes;

            in here what do you mean of m_totalTime? Also, why do a
subtraction of 1 and then multiplied by 1024?

What do you mean of  second.rxBytes in this sentence.

In here should the average throughput increase or decrease? Why?

·      DroppedPackets += iter->second.txPackets - iter->second.rxPackets;

What do you mean second in this code?

Should the drop packet be increased or decreased? Why? In some cases, it
reaches zero? Why?

Why did you get a drop packet? I need a reason? or in another way why does
the drop packet occur in this code?

·      Delay = Delay + (iter->second.delaySum);

Delay = Delay / ReceivedPackets;

What do you mean of second.delaySum in this sentence?

Why do you sum and then divide the delay? Could you explain it more please?

Why is the delay increased?





·       << "Total Lost Packets = " << DroppedPackets <<

<< "Packet Loss ratio = " << ((DroppedPackets*100.00)/SentPackets)<<

In here I misunderstand the formula to explain it more?

Why you got a packet loss? I need a reason? or in another way why the drop
packet occurs in this code?



·      << "Packet delivery ratio = " <<
((ReceivedPackets*100.00)/SentPackets)<<


<< "Packet delivery ratio = " << ReceivedPackets << " / " << SentPackets << "
= " << ((ReceivedPackets*100.00)/SentPackets)<<

In here I misunderstand the formula to explain it more?

The packet delivery ratio should be increased or decreased? Why?


Thank you very much.
